site_name: qml-colors
repo_url: https://github.com/GooRoo/qml-colors
repo_name: GooRoo/qml-colors
edit_uri: "" #edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      accent: orange
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
