site_name: qml-colors
repo_url: https://github.com/GooRoo/qml-colors
repo_name: GooRoo/qml-colors
edit_uri: "" #edit/main/docs/
theme:
  name: material
  logo: assets/qml-colors-logo_64.png
  favicon: assets/qml-colors-logo_32.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      accent: orange
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Why?: getting-started/why.md
    - Basic concepts: getting-started/basic-concepts.md
  - Reference:
    - reference/index.md
    - Color names: reference/color-names.md
    - Units: reference/units.md
    - Tagged literals: reference/tagged-literals.md
