name: tests
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          setup-python: false
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Qbs
        run: |
          sudo apt-get install -y qbs
          qbs setup-toolchains --detect
          qbs setup-qt --detect

      - name: Run tests
        run: qbs build
