name: 'Test Report'
on:
  workflow_run:
    workflows: ['Tests']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Tests
          path: '*.xml'
          reporter: java-junit
