name: tests
on:
  push:
    branches:
      - main
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

  install-tools:
    name: Install Qt and Qbs
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ../Qt
          key: QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          setup-python: false
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          set-env: false

      - name: Install Qbs
        run: sudo apt-get install -y qbs

      - name: Configure Qbs
        run: |
          qbs setup-toolchains --detect
          qbs setup-qt ../Qt/5.15.2/gcc_64/bin/qmake qt515
          qbs config defaultProfile qt515

  test:
    runs-on: ubuntu-latest
    needs:
      - checkout
      - install-tools
    steps:
      - name: Run tests
        run: qbs build
