name: tests
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: /home/runner/work/qml-colors/Qt
          key: QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          setup-python: false
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          set-env: false

      - name: Install Qbs
        run: sudo apt-get install -y qbs

      - name: Configure Qbs
        run: |
          qbs setup-toolchains --detect
          qbs setup-qt ../Qt/5.15.2/gcc_64/bin/qmake qt515
          qbs config defaultProfile qt515

      - name: Run tests
        run: qbs build products.tst_qml.outputToFile:true

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: test-results.xml

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Tests
        path: '*.xml'
        reporter: java-junit
